"""Sample test — auto-generated by goal."""

from typer.testing import CliRunner


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    import vallm  # noqa: F401


def test_cli_app_import_and_help():
    """Verify the CLI app is exported from vallm.cli and runs help."""
    from vallm.cli import app

    runner = CliRunner()
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "Validate LLM-generated code" in result.output
