flowchart LR
    subgraph publish_env_lib
        publish_env__set_cookie["set_cookie"]
        publish_env___is_compatible["_is_compatible"]
        publish_env__valid_ipv4_host_address["valid_ipv4_host_address"]
        publish_env___parse_requirement_details["_parse_requirement_details"]
        publish_env__escapeHtml["escapeHtml"]
        publish_env__copy["copy"]
        publish_env__scheme_is_valid["scheme_is_valid"]
        publish_env__parse_url["parse_url"]
        publish_env__parse_list_header["parse_list_header"]
        publish_env__is_valid_cidr["is_valid_cidr"]
        publish_env___base_version["_base_version"]
        publish_env___toml_key["_toml_key"]
        publish_env__is_normalized_name["is_normalized_name"]
        publish_env___parse_version_many["_parse_version_many"]
        publish_env___parse_marker_item["_parse_marker_item"]
        publish_env____init__["__init__"]
        publish_env___set_children_from_tokens["_set_children_from_tokens"]
        publish_env__text["text"]
        publish_env____get__["__get__"]
        publish_env__parse_tag["parse_tag"]
        publish_env__parse_marker["parse_marker"]
        publish_env__get_netrc_auth["get_netrc_auth"]
        publish_env__extract_zipped_paths["extract_zipped_paths"]
        publish_env____init__["__init__"]
        publish_env___process_metadata_version["_process_metadata_version"]
        publish_env___get_required_sequence_of_objects["_get_required_sequence_of_obje"]
        publish_env____hash__["__hash__"]
        publish_env___glibc_version_string["_glibc_version_string"]
        publish_env__platform_tags["platform_tags"]
        publish_env____delitem__["__delitem__"]
        publish_env__create_cookie["create_cookie"]
        publish_env__path_is_valid["path_is_valid"]
        publish_env__cert_verify["cert_verify"]
        publish_env___compare_greater_than_equal["_compare_greater_than_equal"]
        publish_env__rotate["rotate"]
        publish_env___glibc_version_string_ctypes["_glibc_version_string_ctypes"]
        publish_env___is_linux_armhf["_is_linux_armhf"]
        publish_env__prepare_body["prepare_body"]
        publish_env__renderAttrs["renderAttrs"]
        publish_env__requote_uri["requote_uri"]
        publish_env___process_description_content_type["_process_description_content_t"]
        publish_env___coerce_version["_coerce_version"]
        publish_env__from_parts["from_parts"]
        publish_env__normalize_scheme["normalize_scheme"]
        publish_env__should_bypass_proxies["should_bypass_proxies"]
        publish_env____init__["__init__"]
        publish_env____init__["__init__"]
        publish_env___get_sequence_as["_get_sequence_as"]
        publish_env___public_version["_public_version"]
        publish_env__is_valid_uri["is_valid_uri"]
        publish_env__get_cookie_header["get_cookie_header"]
        publish_env__cast["cast"]
        publish_env___format_marker["_format_marker"]
        publish_env____call__["__call__"]
        publish_env__merge_setting["merge_setting"]
        publish_env__resolve_with["resolve_with"]
        publish_env___get_spec_version["_get_spec_version"]
        publish_env___pad_version["_pad_version"]
        publish_env___version_nodot["_version_nodot"]
        publish_env___parse_extras_list["_parse_extras_list"]
        publish_env__should_strip_auth["should_strip_auth"]
        publish_env__prepare_content_length["prepare_content_length"]
        publish_env__normalizeLink["normalizeLink"]
        publish_env__remove_cookie_by_name["remove_cookie_by_name"]
        publish_env__from_email["from_email"]
        publish_env____eq__["__eq__"]
        publish_env__prepare_auth["prepare_auth"]
        publish_env____hash__["__hash__"]
        publish_env___parse_musl_version["_parse_musl_version"]
        publish_env__parse_sdist_filename["parse_sdist_filename"]
        publish_env__encode_multipart_formdata["encode_multipart_formdata"]
        publish_env__print["print"]
        publish_env__unescapeAll["unescapeAll"]
        publish_env___get_required_as["_get_required_as"]
        publish_env____hash__["__hash__"]
        publish_env___parse_marker["_parse_marker"]
        publish_env__map_domain["map_domain"]
        publish_env___get_musl_version["_get_musl_version"]
        publish_env___normalize_extra_values["_normalize_extra_values"]
        publish_env__encode["encode"]
        publish_env___have_compatible_abi["_have_compatible_abi"]
        publish_env__to_str["to_str"]
        publish_env____init__["__init__"]
        publish_env__get_connection_with_tls_context["get_connection_with_tls_contex"]
        publish_env___generic_abi["_generic_abi"]
        publish_env__default_hooks["default_hooks"]
        publish_env__add_dict_to_cookiejar["add_dict_to_cookiejar"]
        publish_env__normalize["normalize"]
        publish_env__filter["filter"]
        publish_env__remove_dot_segments["remove_dot_segments"]
        publish_env__delete["delete"]
        publish_env____eq__["__eq__"]
        publish_env__get_redirect_target["get_redirect_target"]
        publish_env__platform_tags["platform_tags"]
        publish_env__prepare_cookies["prepare_cookies"]
        publish_env__generate["generate"]
        publish_env__address_in_network["address_in_network"]
        publish_env__host_is_valid["host_is_valid"]
        publish_env__type["type"]
        publish_env__ensure_one_of["ensure_one_of"]
        publish_env__request_url["request_url"]
        publish_env__get_host["get_host"]
        publish_env__from_string["from_string"]
        publish_env__parse["parse"]
        publish_env__normalize_query["normalize_query"]
        publish_env__iter_content["iter_content"]
        publish_env__compatible_tags["compatible_tags"]
        publish_env___encode_params["_encode_params"]
        publish_env__convert_attrs["convert_attrs"]
        publish_env__build_response["build_response"]
        publish_env___validate_header_part["_validate_header_part"]
        publish_env___toml_dict_factory["_toml_dict_factory"]
        publish_env__parse_dict_header["parse_dict_header"]
        publish_env__release_conn["release_conn"]
        publish_env____call__["__call__"]
        publish_env___check_bytes["_check_bytes"]
        publish_env___from_dict["_from_dict"]
        publish_env___implementation["_implementation"]
        publish_env__allow_hosts["allow_hosts"]
        publish_env__default_headers["default_headers"]
        publish_env__unquote_header_value["unquote_header_value"]
        publish_env___parse_requirement_marker["_parse_requirement_marker"]
        publish_env__extract_timestamp["extract_timestamp"]
        publish_env___urllib3_request_context["_urllib3_request_context"]
        publish_env___get_object["_get_object"]
        publish_env__path_is_valid["path_is_valid"]
        publish_env__skipToken["skipToken"]
        publish_env__prepare_headers["prepare_headers"]
        publish_env__interpreter_version["interpreter_version"]
        publish_env___mac_arch["_mac_arch"]
        publish_env__contains["contains"]
        publish_env__items["items"]
        publish_env___linux_platforms["_linux_platforms"]
        publish_env__tokenize["tokenize"]
        publish_env___get_glibc_version["_get_glibc_version"]
        publish_env__resolve_redirects["resolve_redirects"]
        publish_env____post_init__["__post_init__"]
        publish_env____delattr__["__delattr__"]
        publish_env___compare_compatible["_compare_compatible"]
        publish_env__copy_with["copy_with"]
        publish_env__handle_401["handle_401"]
        publish_env__to_ascii["to_ascii"]
        publish_env__prepare_method["prepare_method"]
        publish_env__from_parts["from_parts"]
        publish_env__head["head"]
        publish_env__build_digest_header["build_digest_header"]
        publish_env__prepare_url["prepare_url"]
        publish_env__subauthority_component_is_valid["subauthority_component_is_vali"]
        publish_env__query_is_valid["query_is_valid"]
        publish_env____init__["__init__"]
        publish_env__values["values"]
        publish_env__parseInline["parseInline"]
        publish_env__proxy_headers["proxy_headers"]
        publish_env___validate_path_url["_validate_path_url"]
        publish_env__filter["filter"]
        publish_env___parse_glibc_version["_parse_glibc_version"]
        publish_env___compare_equal["_compare_equal"]
        publish_env____init__["__init__"]
        publish_env__validate["validate"]
        publish_env___encode_files["_encode_files"]
        publish_env__parse_requirement["parse_requirement"]
        publish_env__normalize_fragment["normalize_fragment"]
        publish_env__check_header_validity["check_header_validity"]
        publish_env__code_inline["code_inline"]
        publish_env___abi3_applies["_abi3_applies"]
        publish_env__get["get"]
        publish_env__parse["parse"]
        publish_env___parse_content_type_header["_parse_content_type_header"]
        publish_env__normalizeLinkText["normalizeLinkText"]
        publish_env___get_config_var["_get_config_var"]
        publish_env__platform_tags["platform_tags"]
        publish_env___version_join["_version_join"]
        publish_env____init__["__init__"]
        publish_env__process["process"]
        publish_env___version_split["_version_split"]
        publish_env___parse_marker_op["_parse_marker_op"]
        publish_env__authority_info["authority_info"]
        publish_env___parse_specifier["_parse_specifier"]
        publish_env___toml_value["_toml_value"]
        publish_env__open["open"]
        publish_env___add_child["_add_child"]
        publish_env__guess_json_utf["guess_json_utf"]
        publish_env__process_python_str["process_python_str"]
        publish_env__get_auth_from_url["get_auth_from_url"]
        publish_env____init__["__init__"]
        publish_env__decrypt["decrypt"]
        publish_env__get_environ_proxies["get_environ_proxies"]
        publish_env__decode["decode"]
        publish_env___is_threaded_cpython["_is_threaded_cpython"]
        publish_env___get_sequence_of_objects["_get_sequence_of_objects"]
        publish_env___normalize_extras["_normalize_extras"]
        publish_env__list["list"]
        publish_env___generate_authority["_generate_authority"]
        publish_env___normalize_string["_normalize_string"]
        publish_env___from_dict["_from_dict"]
        publish_env__fence["fence"]
        publish_env__main["main"]
        publish_env___copy_cookie_jar["_copy_cookie_jar"]
        publish_env__contains["contains"]
        publish_env__rebuild_auth["rebuild_auth"]
        publish_env__attrItems["attrItems"]
        publish_env__keys["keys"]
        publish_env__ensure_required_components_exist["ensure_required_components_exi"]
        publish_env__select_proxy["select_proxy"]
        publish_env__proxy_from_url["proxy_from_url"]
        publish_env__close["close"]
        publish_env__filter["filter"]
        publish_env__sys_tags["sys_tags"]
        publish_env__attrIndex["attrIndex"]
        publish_env__from_string["from_string"]
        publish_env___basic_auth_str["_basic_auth_str"]
        publish_env__check_password["check_password"]
        publish_env__build_connection_pool_key_attributes["build_connection_pool_key_attr"]
        publish_env___get["_get"]
        publish_env__query_is_valid["query_is_valid"]
        publish_env__from_string["from_string"]
        publish_env__hasattr["hasattr"]
        publish_env__proxy_manager_for["proxy_manager_for"]
        publish_env__as_dict["as_dict"]
        publish_env___parse_marker_atom["_parse_marker_atom"]
        publish_env__validateLink["validateLink"]
        publish_env__normalize_percent_characters["normalize_percent_characters"]
        publish_env__super_len["super_len"]
        publish_env__authority_from["authority_from"]
        publish_env__iter_slices["iter_slices"]
        publish_env___from_dict["_from_dict"]
        publish_env__format_full_version["format_full_version"]
        publish_env__copy_with["copy_with"]
        publish_env___py_interpreter_range["_py_interpreter_range"]
        publish_env__rebuild_proxies["rebuild_proxies"]
        publish_env__init_per_thread_state["init_per_thread_state"]
        publish_env___compare_greater_than["_compare_greater_than"]
        publish_env__to_key_val_list["to_key_val_list"]
        publish_env__fragment_is_valid["fragment_is_valid"]
        publish_env__normalizeLink["normalizeLink"]
        publish_env__normalize_path["normalize_path"]
        publish_env__urldefragauth["urldefragauth"]
        publish_env__parse_email["parse_email"]
        publish_env__ios_platforms["ios_platforms"]
        publish_env__get_full_url["get_full_url"]
        publish_env___parse_marker_var["_parse_marker_var"]
        publish_env___is_linux_i686["_is_linux_i686"]
        publish_env__set["set"]
        publish_env__get_encoding_from_headers["get_encoding_from_headers"]
        publish_env__hash["hash"]
        publish_env__morsel_to_cookie["morsel_to_cookie"]
        publish_env__set["set"]
        publish_env____init__["__init__"]
        publish_env__map["map"]
        publish_env__normalize_host["normalize_host"]
        publish_env__split_authority["split_authority"]
        publish_env__unquote_unreserved["unquote_unreserved"]
        publish_env__dispatch_hook["dispatch_hook"]
        publish_env____eq__["__eq__"]
        publish_env____hash__["__hash__"]
        publish_env__interpreter_name["interpreter_name"]
        publish_env____hash__["__hash__"]
        publish_env__scheme_is_valid["scheme_is_valid"]
        publish_env__put["put"]
        publish_env__generic_tags["generic_tags"]
        publish_env____init__["__init__"]
        publish_env___validate_normalized_name["_validate_normalized_name"]
        publish_env__normalize_uri["normalize_uri"]
        publish_env____init__["__init__"]
        publish_env__json["json"]
        publish_env__process_env_var["process_env_var"]
        publish_env__encode_component["encode_component"]
        publish_env__to_native_string["to_native_string"]
        publish_env__merge_environment_settings["merge_environment_settings"]
        publish_env__cpython_tags["cpython_tags"]
        publish_env__code_block["code_block"]
        publish_env____init__["__init__"]
        publish_env__extract_cookies_to_jar["extract_cookies_to_jar"]
        publish_env__normalizeLinkText["normalizeLinkText"]
        publish_env__decrypt_at_time["decrypt_at_time"]
        publish_env___normalize["_normalize"]
        publish_env___parse_extras["_parse_extras"]
        publish_env___check_cryptography["_check_cryptography"]
        publish_env__urlparse["urlparse"]
        publish_env____init__["__init__"]
        publish_env__prepend_scheme_if_needed["prepend_scheme_if_needed"]
        publish_env___get_unverified_token_data["_get_unverified_token_data"]
        publish_env__rule["rule"]
        publish_env__get_unicode_from_response["get_unicode_from_response"]
        publish_env__dotted_netmask["dotted_netmask"]
        publish_env__is_valid["is_valid"]
        publish_env__uri_reference["uri_reference"]
        publish_env__info["info"]
        publish_env__cookiejar_from_dict["cookiejar_from_dict"]
        publish_env__default_environment["default_environment"]
        publish_env__iri_reference["iri_reference"]
        publish_env____setstate__["__setstate__"]
        publish_env__register_hook["register_hook"]
        publish_env___get_as["_get_as"]
        publish_env__post["post"]
        publish_env___mac_binary_formats["_mac_binary_formats"]
        publish_env___from_dict["_from_dict"]
        publish_env__ensure_components_are_valid["ensure_components_are_valid"]
        publish_env___process_dynamic["_process_dynamic"]
        publish_env__normalize_authority["normalize_authority"]
        publish_env__options["options"]
        publish_env____init__["__init__"]
        publish_env__bytes["bytes"]
        publish_env__validateLink["validateLink"]
        publish_env___cpython_abis["_cpython_abis"]
        publish_env__unsplit["unsplit"]
        publish_env___parse_requirement["_parse_requirement"]
        publish_env__canonicalize_name["canonicalize_name"]
        publish_env__patch["patch"]
        publish_env__merge_hooks["merge_hooks"]
        publish_env__prepare_request["prepare_request"]
        publish_env__fragment_is_valid["fragment_is_valid"]
        publish_env___parse_full_marker["_parse_full_marker"]
        publish_env__default_user_agent["default_user_agent"]
        publish_env__set_environ["set_environ"]
        publish_env____repr__["__repr__"]
        publish_env__resolve_proxies["resolve_proxies"]
        publish_env___from_dict["_from_dict"]
        publish_env__stream_decode_response_unicode["stream_decode_response_unicode"]
        publish_env___evaluate_markers["_evaluate_markers"]
        publish_env__delattr["delattr"]
        publish_env____str__["__str__"]
        publish_env__authority_is_valid["authority_is_valid"]
        publish_env__is_ipv4_address["is_ipv4_address"]
        publish_env___from_dict["_from_dict"]
        publish_env___get_payload["_get_payload"]
        publish_env___parse_elf["_parse_elf"]
        publish_env___from_dict["_from_dict"]
        publish_env____init__["__init__"]
        publish_env__to_bytes["to_bytes"]
        publish_env__merge_cookies["merge_cookies"]
        publish_env___encrypt_from_parts["_encrypt_from_parts"]
        publish_env__encode["encode"]
        publish_env__request["request"]
        publish_env__from_string["from_string"]
        publish_env__urlencode["urlencode"]
        publish_env__encode["encode"]
        publish_env__allow_schemes["allow_schemes"]
        publish_env___get_sequence["_get_sequence"]
        publish_env___get_required["_get_required"]
        publish_env___compare_less_than_equal["_compare_less_than_equal"]
        publish_env___glibc_version_string_confstr["_glibc_version_string_confstr"]
        publish_env__canonicalize_version["canonicalize_version"]
        publish_env___generic_platforms["_generic_platforms"]
        publish_env__tokenize["tokenize"]
        publish_env__get_connection["get_connection"]
        publish_env__mac_platforms["mac_platforms"]
        publish_env__parse_wheel_filename["parse_wheel_filename"]
        publish_env____init__["__init__"]
        publish_env__to_unicode["to_unicode"]
        publish_env___compare_less_than["_compare_less_than"]
        publish_env__android_platforms["android_platforms"]
        publish_env__authority_is_valid["authority_is_valid"]
        publish_env__dict_to_sequence["dict_to_sequence"]
    end
    subgraph scripts_bump_version
        scripts__bump_version__bump_version["bump_version"]
        scripts__bump_version__main["main"]
    end
    scripts__bump_version__bump_version --> publish_env__map
    scripts__bump_version__main --> scripts__bump_version__bump_version
    scripts__bump_version__main --> publish_env__print
    publish_env____init__ --> publish_env__to_str
    publish_env____init__ --> publish_env__list
    publish_env____init__ --> publish_env__unsplit
    publish_env___encrypt_from_parts --> publish_env___check_bytes
    publish_env__decrypt --> publish_env___get_unverified_token_data
    publish_env__decrypt_at_time --> publish_env___get_unverified_token_data
    publish_env__extract_timestamp --> publish_env___get_unverified_token_data
    publish_env__rotate --> publish_env___get_unverified_token_data
    publish_env__uri_reference --> publish_env__from_string
    publish_env__iri_reference --> publish_env__from_string
    publish_env__is_valid_uri --> publish_env__from_string
    publish_env__normalize_uri --> publish_env__from_string
    publish_env__urlparse --> publish_env__from_string
    publish_env__normalize_authority --> publish_env__normalize_host
    publish_env__normalize_authority --> publish_env__normalize_percent_characters
    publish_env__normalize_path --> publish_env__normalize_percent_characters
    publish_env__normalize_path --> publish_env__remove_dot_segments
    publish_env__normalize_query --> publish_env__normalize_percent_characters
    publish_env__normalize_fragment --> publish_env__normalize_percent_characters
    publish_env__normalize_percent_characters --> publish_env__set
    publish_env__encode_component --> publish_env__to_bytes
    publish_env____init__ --> publish_env__set
    publish_env__allow_schemes --> publish_env__normalize_scheme
    publish_env__allow_hosts --> publish_env__normalize_host
    publish_env__validate --> publish_env__ensure_one_of
    publish_env__validate --> publish_env__check_password
    publish_env__validate --> publish_env__ensure_required_components_exist
    publish_env__validate --> publish_env__ensure_components_are_valid
    publish_env__authority_is_valid --> publish_env__is_valid
    publish_env__authority_is_valid --> publish_env__host_is_valid
    publish_env__host_is_valid --> publish_env__is_valid
    publish_env__host_is_valid --> publish_env__valid_ipv4_host_address
    publish_env__scheme_is_valid --> publish_env__is_valid
    publish_env__path_is_valid --> publish_env__is_valid
    publish_env__query_is_valid --> publish_env__is_valid
    publish_env__fragment_is_valid --> publish_env__is_valid
    publish_env__subauthority_component_is_valid --> publish_env__host_is_valid
    publish_env__ensure_components_are_valid --> publish_env__set
    publish_env__ensure_components_are_valid --> publish_env__subauthority_component_is_valid
    publish_env__to_str --> publish_env__hasattr
    publish_env__to_bytes --> publish_env__hasattr
    publish_env____delattr__ --> publish_env__delattr
    publish_env__authority_info --> publish_env__valid_ipv4_host_address
    publish_env__authority_is_valid --> publish_env__authority_is_valid
    publish_env__scheme_is_valid --> publish_env__scheme_is_valid
    publish_env__path_is_valid --> publish_env__path_is_valid
    publish_env__query_is_valid --> publish_env__query_is_valid
    publish_env__fragment_is_valid --> publish_env__fragment_is_valid
    publish_env__resolve_with --> publish_env__type
    publish_env__resolve_with --> publish_env__normalize_path
    publish_env__copy_with --> publish_env__list
    publish_env__process --> publish_env__rule
    publish_env__tokenize --> publish_env__rule
    publish_env____eq__ --> publish_env__from_string
    publish_env____eq__ --> publish_env__type
    publish_env__normalize --> publish_env__normalize_scheme
    publish_env__normalize --> publish_env__normalize_authority
    publish_env__normalize --> publish_env__normalize_path
    publish_env__normalize --> publish_env__normalize_query
    publish_env__normalize --> publish_env__normalize_fragment
    publish_env__from_string --> publish_env__to_str
    publish_env__from_string --> publish_env__encode_component
    publish_env__encode --> publish_env__to_str
    publish_env__encode --> publish_env__encode_component
    publish_env___generate_authority --> publish_env__normalize_authority
    publish_env___generate_authority --> publish_env__to_str
    publish_env__from_parts --> publish_env__authority_from
    publish_env__from_string --> publish_env__from_string
    publish_env__from_string --> publish_env__authority_from
    publish_env__encode --> publish_env__hasattr
    publish_env__from_parts --> publish_env__to_bytes
    publish_env__from_string --> publish_env__to_bytes
    publish_env__copy_with --> publish_env__hasattr
    publish_env__copy_with --> publish_env__to_str
    publish_env__authority_from --> publish_env__split_authority
    publish_env__skipToken --> publish_env__rule
    publish_env__parse --> publish_env__rule
    publish_env__renderAttrs --> publish_env__escapeHtml
    publish_env__code_inline --> publish_env__escapeHtml
    publish_env__code_block --> publish_env__escapeHtml
    publish_env__fence --> publish_env__escapeHtml
    publish_env__fence --> publish_env__unescapeAll
    publish_env__text --> publish_env__escapeHtml
    publish_env__to_unicode --> publish_env__map_domain
    publish_env__to_unicode --> publish_env__decode
    publish_env__to_ascii --> publish_env__map_domain
    publish_env__to_ascii --> publish_env__encode
    publish_env__parse --> publish_env__type
    publish_env__parseInline --> publish_env__type
    publish_env__validateLink --> publish_env__validateLink
    publish_env__normalizeLink --> publish_env__normalizeLink
    publish_env__normalizeLinkText --> publish_env__normalizeLinkText
    publish_env____repr__ --> publish_env__type
    publish_env___add_child --> publish_env__type
    publish_env___set_children_from_tokens --> publish_env__list
    publish_env____init__ --> publish_env__cast
    publish_env__info --> publish_env___implementation
    publish_env__main --> publish_env__print
    publish_env__main --> publish_env__info
    publish_env____init__ --> publish_env__urlparse
    publish_env__get_host --> publish_env__urlparse
    publish_env__get_full_url --> publish_env__to_native_string
    publish_env__get_full_url --> publish_env__urlparse
    publish_env__extract_cookies_to_jar --> publish_env__hasattr
    publish_env__set --> publish_env__remove_cookie_by_name
    publish_env__set --> publish_env__morsel_to_cookie
    publish_env__set --> publish_env__create_cookie
    publish_env__keys --> publish_env__list
    publish_env__values --> publish_env__list
    publish_env__items --> publish_env__list
    publish_env____delitem__ --> publish_env__remove_cookie_by_name
    publish_env__set_cookie --> publish_env__hasattr
    publish_env___copy_cookie_jar --> publish_env__hasattr
    publish_env__create_cookie --> publish_env__set
    publish_env__create_cookie --> publish_env__list
    publish_env__morsel_to_cookie --> publish_env__create_cookie
    publish_env__cookiejar_from_dict --> publish_env__create_cookie
    publish_env__merge_cookies --> publish_env__cookiejar_from_dict
    publish_env___urllib3_request_context --> publish_env__urlparse
    publish_env__proxy_manager_for --> publish_env__get_auth_from_url
    publish_env__proxy_manager_for --> publish_env__proxy_from_url
    publish_env__cert_verify --> publish_env__extract_zipped_paths
    publish_env__build_response --> publish_env__get_encoding_from_headers
    publish_env__build_response --> publish_env__extract_cookies_to_jar
    publish_env__build_connection_pool_key_attributes --> publish_env___urllib3_request_context
    publish_env__get_connection_with_tls_context --> publish_env__select_proxy
    publish_env__get_connection_with_tls_context --> publish_env__prepend_scheme_if_needed
    publish_env__get_connection_with_tls_context --> publish_env__parse_url
    publish_env__get_connection --> publish_env__select_proxy
    publish_env__get_connection --> publish_env__prepend_scheme_if_needed
    publish_env__get_connection --> publish_env__parse_url
    publish_env__get_connection --> publish_env__urlparse
    publish_env__request_url --> publish_env__select_proxy
    publish_env__request_url --> publish_env__urlparse
    publish_env__request_url --> publish_env__urldefragauth
    publish_env__proxy_headers --> publish_env__get_auth_from_url
    publish_env__proxy_headers --> publish_env___basic_auth_str
    publish_env___check_cryptography --> publish_env__list
    publish_env___check_cryptography --> publish_env__map
    publish_env__merge_setting --> publish_env__to_key_val_list
    publish_env__merge_hooks --> publish_env__merge_setting
    publish_env__get_redirect_target --> publish_env__to_native_string
    publish_env__should_strip_auth --> publish_env__urlparse
    publish_env__resolve_redirects --> publish_env__urlparse
    publish_env__resolve_redirects --> publish_env__to_native_string
    publish_env__rebuild_auth --> publish_env__get_netrc_auth
    publish_env__rebuild_proxies --> publish_env__resolve_proxies
    publish_env__rebuild_proxies --> publish_env__urlparse
    publish_env__rebuild_proxies --> publish_env__get_auth_from_url
    publish_env__rebuild_proxies --> publish_env___basic_auth_str
    publish_env____init__ --> publish_env__default_headers
    publish_env____init__ --> publish_env__default_hooks
    publish_env____init__ --> publish_env__cookiejar_from_dict
    publish_env__prepare_request --> publish_env__merge_cookies
    publish_env__prepare_request --> publish_env__cookiejar_from_dict
    publish_env__prepare_request --> publish_env__get_netrc_auth
    publish_env__prepare_request --> publish_env__merge_setting
    publish_env__merge_environment_settings --> publish_env__merge_setting
    publish_env__merge_environment_settings --> publish_env__get_environ_proxies
    publish_env____call__ --> publish_env___basic_auth_str
    publish_env__init_per_thread_state --> publish_env__hasattr
    publish_env__build_digest_header --> publish_env__urlparse
    publish_env__handle_401 --> publish_env__parse_dict_header
    publish_env__handle_401 --> publish_env__extract_cookies_to_jar
    publish_env__get --> publish_env__request
    publish_env__options --> publish_env__request
    publish_env__head --> publish_env__request
    publish_env__post --> publish_env__request
    publish_env__put --> publish_env__request
    publish_env__patch --> publish_env__request
    publish_env__delete --> publish_env__request
    publish_env__dispatch_hook --> publish_env__hasattr
    publish_env____post_init__ --> publish_env__convert_attrs
    publish_env__attrIndex --> publish_env__list
    publish_env__attrItems --> publish_env__list
    publish_env__as_dict --> publish_env__filter
    publish_env__dict_to_sequence --> publish_env__hasattr
    publish_env__super_len --> publish_env__hasattr
    publish_env__get_netrc_auth --> publish_env__urlparse
    publish_env__to_key_val_list --> publish_env__list
    publish_env__parse_list_header --> publish_env__unquote_header_value
    publish_env__parse_dict_header --> publish_env__unquote_header_value
    publish_env__add_dict_to_cookiejar --> publish_env__cookiejar_from_dict
    publish_env__get_encoding_from_headers --> publish_env___parse_content_type_header
    publish_env__get_unicode_from_response --> publish_env__get_encoding_from_headers
    publish_env__requote_uri --> publish_env__unquote_unreserved
    publish_env__address_in_network --> publish_env__dotted_netmask
    publish_env__should_bypass_proxies --> publish_env__urlparse
    publish_env__should_bypass_proxies --> publish_env__is_ipv4_address
    publish_env__should_bypass_proxies --> publish_env__set_environ
    publish_env__should_bypass_proxies --> publish_env__is_valid_cidr
    publish_env__get_environ_proxies --> publish_env__should_bypass_proxies
    publish_env__select_proxy --> publish_env__urlparse
    publish_env__resolve_proxies --> publish_env__urlparse
    publish_env__resolve_proxies --> publish_env__get_environ_proxies
    publish_env__resolve_proxies --> publish_env__should_bypass_proxies
    publish_env__default_headers --> publish_env__default_user_agent
    publish_env__prepend_scheme_if_needed --> publish_env__parse_url
    publish_env__get_auth_from_url --> publish_env__urlparse
    publish_env__check_header_validity --> publish_env___validate_header_part
    publish_env___validate_header_part --> publish_env__type
    publish_env__urldefragauth --> publish_env__urlparse
    publish_env___encode_params --> publish_env__hasattr
    publish_env___encode_params --> publish_env__to_key_val_list
    publish_env___encode_params --> publish_env__urlencode
    publish_env___encode_files --> publish_env__to_key_val_list
    publish_env___encode_files --> publish_env__encode_multipart_formdata
    publish_env__register_hook --> publish_env__hasattr
    publish_env__copy --> publish_env___copy_cookie_jar
    publish_env__prepare_method --> publish_env__to_native_string
    publish_env__prepare_url --> publish_env__requote_uri
    publish_env__prepare_url --> publish_env__parse_url
    publish_env__prepare_headers --> publish_env__check_header_validity
    publish_env__prepare_headers --> publish_env__to_native_string
    publish_env__prepare_body --> publish_env__hasattr
    publish_env__prepare_body --> publish_env__super_len
    publish_env__prepare_content_length --> publish_env__super_len
    publish_env__prepare_auth --> publish_env__get_auth_from_url
    publish_env__prepare_cookies --> publish_env__get_cookie_header
    publish_env__prepare_cookies --> publish_env__cookiejar_from_dict
    publish_env__iter_content --> publish_env__iter_slices
    publish_env__iter_content --> publish_env__generate
    publish_env__iter_content --> publish_env__hasattr
    publish_env__iter_content --> publish_env__stream_decode_response_unicode
    publish_env__json --> publish_env__guess_json_utf
    publish_env__close --> publish_env__release_conn
    publish_env__parse_requirement --> publish_env___parse_requirement
    publish_env___parse_requirement --> publish_env___parse_extras
    publish_env___parse_requirement --> publish_env___parse_requirement_details
    publish_env___parse_requirement_details --> publish_env___parse_requirement_marker
    publish_env___parse_requirement_details --> publish_env___parse_specifier
    publish_env___parse_requirement_marker --> publish_env___parse_marker
    publish_env___parse_extras --> publish_env___parse_extras_list
    publish_env___parse_specifier --> publish_env___parse_version_many
    publish_env__parse_marker --> publish_env___parse_full_marker
    publish_env___parse_full_marker --> publish_env___parse_marker
    publish_env___parse_marker --> publish_env___parse_marker_atom
    publish_env___parse_marker_atom --> publish_env___parse_marker_item
    publish_env___parse_marker_atom --> publish_env___parse_marker
    publish_env___parse_marker_item --> publish_env___parse_marker_var
    publish_env___parse_marker_item --> publish_env___parse_marker_op
    publish_env___parse_marker_var --> publish_env__process_env_var
    publish_env___parse_marker_var --> publish_env__process_python_str
    publish_env____init__ --> publish_env___parse_requirement
    publish_env____init__ --> publish_env___normalize_extra_values
    publish_env____hash__ --> publish_env__hash
    publish_env____hash__ --> publish_env__canonicalize_name
    publish_env____eq__ --> publish_env__canonicalize_name
    publish_env___parse_elf --> publish_env__open
    publish_env___is_linux_armhf --> publish_env___parse_elf
    publish_env___is_linux_i686 --> publish_env___parse_elf
    publish_env___have_compatible_abi --> publish_env___is_linux_armhf
    publish_env___have_compatible_abi --> publish_env___is_linux_i686
    publish_env___glibc_version_string --> publish_env___glibc_version_string_confstr
    publish_env___glibc_version_string --> publish_env___glibc_version_string_ctypes
    publish_env___get_glibc_version --> publish_env___glibc_version_string
    publish_env___get_glibc_version --> publish_env___parse_glibc_version
    publish_env___is_compatible --> publish_env___get_glibc_version
    publish_env___is_compatible --> publish_env__hasattr
    publish_env__platform_tags --> publish_env___have_compatible_abi
    publish_env__platform_tags --> publish_env__set
    publish_env__platform_tags --> publish_env___get_glibc_version
    publish_env____init__ --> publish_env__bytes
    publish_env____init__ --> publish_env__hasattr
    publish_env__parse_email --> publish_env___get_payload
    publish_env__parse_email --> publish_env__cast
    publish_env____get__ --> publish_env__cast
    publish_env___process_metadata_version --> publish_env__cast
    publish_env___process_description_content_type --> publish_env__list
    publish_env___process_dynamic --> publish_env__map
    publish_env___process_dynamic --> publish_env__list
    publish_env__from_email --> publish_env__parse_email
    publish_env__canonicalize_name --> publish_env__cast
    publish_env__parse_wheel_filename --> publish_env__canonicalize_name
    publish_env__parse_wheel_filename --> publish_env__parse_tag
    publish_env__parse_sdist_filename --> publish_env__canonicalize_name
    publish_env___get_spec_version --> publish_env___coerce_version
    publish_env___compare_compatible --> publish_env___version_join
    publish_env___compare_compatible --> publish_env__list
    publish_env___compare_compatible --> publish_env___version_split
    publish_env___compare_equal --> publish_env__canonicalize_version
    publish_env___compare_equal --> publish_env___version_split
    publish_env___compare_equal --> publish_env___pad_version
    publish_env___compare_equal --> publish_env___public_version
    publish_env___compare_less_than_equal --> publish_env___public_version
    publish_env___compare_greater_than_equal --> publish_env___public_version
    publish_env___compare_less_than --> publish_env___base_version
    publish_env___compare_greater_than --> publish_env___base_version
    publish_env__contains --> publish_env__list
    publish_env__filter --> publish_env___coerce_version
    publish_env___pad_version --> publish_env__list
    publish_env____init__ --> publish_env__map
    publish_env__contains --> publish_env___coerce_version
    publish_env___toml_dict_factory --> publish_env___toml_key
    publish_env___toml_dict_factory --> publish_env___toml_value
    publish_env___get --> publish_env__type
    publish_env___get_required --> publish_env___get
    publish_env___get_sequence --> publish_env___get
    publish_env___get_sequence --> publish_env__type
    publish_env___get_as --> publish_env___get
    publish_env___get_required_as --> publish_env___get_as
    publish_env___get_sequence_as --> publish_env___get_sequence
    publish_env___get_object --> publish_env___get
    publish_env___get_sequence_of_objects --> publish_env___get_sequence
    publish_env___get_required_sequence_of_objects --> publish_env___get_sequence_of_objects
    publish_env___validate_normalized_name --> publish_env__is_normalized_name
    publish_env___from_dict --> publish_env___validate_path_url
    publish_env___from_dict --> publish_env___get_required
    publish_env___from_dict --> publish_env___get
    publish_env___from_dict --> publish_env___get_required_as
    publish_env___from_dict --> publish_env___get_as
    publish_env___from_dict --> publish_env___get_sequence_as
    publish_env___from_dict --> publish_env___get_sequence
    publish_env___get_musl_version --> publish_env___parse_musl_version
    publish_env___get_musl_version --> publish_env__open
    publish_env__platform_tags --> publish_env___get_musl_version
    publish_env____init__ --> publish_env__hash
    publish_env____setstate__ --> publish_env__hash
    publish_env__parse_tag --> publish_env__set
    publish_env___cpython_abis --> publish_env___version_nodot
    publish_env___cpython_abis --> publish_env___get_config_var
    publish_env___cpython_abis --> publish_env__hasattr
    publish_env__cpython_tags --> publish_env__list
    publish_env__cpython_tags --> publish_env___is_threaded_cpython
    publish_env__cpython_tags --> publish_env___abi3_applies
    publish_env__cpython_tags --> publish_env___version_nodot
    publish_env__cpython_tags --> publish_env___cpython_abis
    publish_env__cpython_tags --> publish_env__platform_tags
    publish_env___generic_abi --> publish_env___get_config_var
    publish_env___generic_abi --> publish_env___cpython_abis
    publish_env___generic_abi --> publish_env___normalize_string
    publish_env__generic_tags --> publish_env__list
    publish_env__generic_tags --> publish_env__interpreter_name
    publish_env__generic_tags --> publish_env__interpreter_version
    publish_env__generic_tags --> publish_env___generic_abi
    publish_env__generic_tags --> publish_env__platform_tags
    publish_env___py_interpreter_range --> publish_env___version_nodot
    publish_env__compatible_tags --> publish_env__list
    publish_env__compatible_tags --> publish_env___py_interpreter_range
    publish_env__compatible_tags --> publish_env__platform_tags
    publish_env__mac_platforms --> publish_env__cast
    publish_env__mac_platforms --> publish_env___mac_arch
    publish_env__mac_platforms --> publish_env___mac_binary_formats
    publish_env__ios_platforms --> publish_env__cast
    publish_env__ios_platforms --> publish_env__map
    publish_env__android_platforms --> publish_env___normalize_string
    publish_env___linux_platforms --> publish_env___normalize_string
    publish_env___generic_platforms --> publish_env___normalize_string
    publish_env__platform_tags --> publish_env__mac_platforms
    publish_env__platform_tags --> publish_env__ios_platforms
    publish_env__platform_tags --> publish_env__android_platforms
    publish_env__platform_tags --> publish_env___linux_platforms
    publish_env__platform_tags --> publish_env___generic_platforms
    publish_env__interpreter_version --> publish_env___get_config_var
    publish_env__interpreter_version --> publish_env___version_nodot
    publish_env___version_nodot --> publish_env__map
    publish_env__sys_tags --> publish_env__interpreter_name
    publish_env__sys_tags --> publish_env__compatible_tags
    publish_env__sys_tags --> publish_env__cpython_tags
    publish_env__sys_tags --> publish_env__generic_tags
    publish_env__sys_tags --> publish_env__interpreter_version
    publish_env___normalize_extras --> publish_env__canonicalize_name
    publish_env___normalize_extra_values --> publish_env___normalize_extras
    publish_env___normalize --> publish_env__canonicalize_name
    publish_env___evaluate_markers --> publish_env___normalize
    publish_env__default_environment --> publish_env__format_full_version
    publish_env____init__ --> publish_env___parse_marker
    publish_env____str__ --> publish_env___format_marker
